# Generated by Django 3.0.5 on 2023-07-20 13:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LibraryApp', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BookAdd',
        ),
    ]
