# Generated by Django 3.0.5 on 2023-07-20 13:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('LibraryApp', '0002_delete_bookadd'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookAdd',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('btitle', models.CharField(max_length=50)),
                ('bauthor', models.CharField(max_length=50)),
                ('bedition', models.CharField(max_length=20)),
                ('bdes', models.TextField()),
                ('bstatus', models.BooleanField(default=False)),
                ('add_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
