# Generated by Django 3.0.5 on 2023-07-24 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LibraryApp', '0003_bookadd'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookadd',
            name='bdept',
            field=models.CharField(choices=[('G', '----- Select Branch -----'), ('CSE', 'Computer Science and Engineering'), ('ECE', 'Electrical and Communication Engineering'), ('EEE', 'Electrical and Electronics Engineering'), ('CIVIL', 'Civil Engineering'), ('MECH', 'Mechanical Engineering')], default='G', max_length=50),
        ),
    ]
