# Generated by Django 3.0.5 on 2023-07-27 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LibraryApp', '0005_bookrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookrequest',
            name='approved_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
