# Generated by Django 3.0.5 on 2023-07-29 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LibraryApp', '0008_bookrequest_requested_by_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookrequest',
            name='return_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
