# Generated by Django 3.0.5 on 2023-07-30 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LibraryApp', '0009_bookrequest_return_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookrequest',
            name='approved_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
