# Generated by Django 3.0.5 on 2023-07-30 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LibraryApp', '0010_auto_20230730_1630'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookrequest',
            name='status',
        ),
        migrations.AddField(
            model_name='bookrequest',
            name='fine_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
    ]
