# Generated by Django 3.0.5 on 2023-08-14 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LibraryApp', '0012_remove_bookrequest_fine_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookrequest',
            name='due_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bookrequest',
            name='fine_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
    ]
