# Generated by Django 3.0.5 on 2023-08-14 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LibraryApp', '0013_auto_20230814_1135'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookadd',
            name='num_copies',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
